### ISSUE TITLE
Register Button

### ISSUE THREAD

**Issue by RahulSondhi** [RahulSondhi/Tipsy#12]
You can spam the register button while its registering and spam email.

**Steps to Reproduce:**

1. User completes registration form.
2. When clicking the Register button, the form will not clear.
3. An impatient user can spam press the register button and send multiple register API calls. This harms the backend server with multiple requests

**What we should expect:**
After clicking the register button, the form should clear completely on the frontend while still making the API call to register a user on the backend

**TODO:**
Clear the form properly and send the register API call. This should prevent users from spamming the button and sending multiple confirmation emails.

**Comment by bvalarezo** [comment]
You should look into clearing the Form after clicking the Register button, making sure that new users can't spam a Register Request to the backend

**Comment by bvalarezo** [comment]
Needs more testing...
Was able to implement a version of this that works so far. Need more trials in order to confirm
