### ISSUE TITLE
First name field icon doesn't move properly

### ISSUE THREAD

**Issue by ialmosara** [RahulSondhi/Tipsy#31]
On the Settings page if you scroll up and down the icon in the First Name field trails behind and doesn't consistently stay in the input box.

Steps to Reproduce:

1. Logged in User navigates to the Settings page
2. User scrolls up and down really fast and sees the icon trail behind the field box.

What we should expect:
The the icon should never leave the box initially.

TODO:
Make the position of the icon static relative to the input box so it stays in position.

**Comment by bvalarezo** [comment]
Tested this on my Thinkpad-t450s

Unable to reproduce bug on Firefox or Chrome. This graphical error is related to the client.

Won't fix
