### ISSUE TITLE
Dummy User gets displayed admin account when clicking on My Profile

### ISSUE THREAD

**Issue by ialmosara** [RahulSondhi/Tipsy#33]
Dummy User gets displayed admin account when clicking on the My Profile tab while having an admin account's display page loaded.

Steps to Reproduce:

1. Dummy 2 user logs in 
2. User goes on the My Bars page
3. User clicks Cindy's Bar 2
4. User clicks on the owner profile (bryan)
5. User hovers over the account tab in the navigation bar and clicks on my profile
6. User gets displayed the admin account

On any other page the dummy user views their own profile and not an admin's

What we should expect:
After clicking on the My Profile tab the user should see their own profile and not an admin's profile. 

TODO:

**Comment by RahulSondhi** [comment]
This feature wasnt done being coded. How can you make a bug about something thats not coded. read messenger
