### ISSUE TITLE
Unable to remove workers & managers from Bar

### ISSUE THREAD

**Issue by ialmosara** [RahulSondhi/Tipsy#35]
After going into Bar settings and clicking on the red X button next to a Worker or Manager to remove and click save, these users still appear after re-navigating back to the Bar profile.

Steps to Reproduce:
1: Logged in as user bryan (bryan@email.com)
2. Navigated to Cindy's Bar 2
3. Clicked on Bar settings
4. Removed all workers & managers and clicked save
5. After going back to my bars and viewing the Bar profile again, you can see that these users are still affiliated with the Bar.

What we should expect:
After removing all workers & managers and clicking save, the bar profile should not still have these users associated with the bar.

TODO:
Check where managers and workers being removed from a bar are being handled and see if these changes save to the database.

**Comment by bvalarezo** [comment]
Can you confirm that React is sending a POST with the barsettings API call? Do the tables for Bar and User get updated in MongoDB after saving changes? What status codes are being returned when editing a bar? Is this also true for other fields like description, img, and name?
